### ISSUE TITLE
tar: Ignoring unknown extended header keyword

### ISSUE THREAD

**Issue by Vini2** [gbouras13/plassembler#18]
**Describe the bug**
The following messages are displayed when downloading the databases.

```
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
```

**To Reproduce**
1. Run the command `install_database.py -d <path>`

**Expected behavior**
If possible suppress these messages. It might be an issue with tar files created on macOS that creates some extra info that is not recognized by GNU tar.

**Screenshots**

macOS
<img width="1029" alt="Screenshot 2023-05-25 at 9 29 07 am" src="https://github.com/gbouras13/plassembler/assets/12206048/68cc4cdd-9628-498f-b296-093f1dbfe94c">

Linux
<img width="1198" alt="Screenshot 2023-05-25 at 9 42 58 am" src="https://github.com/gbouras13/plassembler/assets/12206048/fbc0a422-9701-4ac6-a602-52f29431ca88">

**Comment by gbouras13** [comment]
Fixed by #21 PR - subprocess calls removed in favour of native python commands
