### ISSUE TITLE
searching against PLSDB as an additional option in plassembler

### ISSUE THREAD

**Issue by gaworj** [gbouras13/plassembler#36]
Hi,

Thanks again for such a great tool! It is great to see new plassembler options.

Can you also add an option to search for user-supplied plasmids against PLDSB?

Bests,
Jan

**Comment by gbouras13** [comment]
Hi @gaworj ,

Thanks mate - let me know if you have any feedback on the `long` mode especially.

Do you mean to use mash to query input assemblies against the PLSDB? Like `plassembler assembled` with no copy number estimation?

Maybe I can just add a `--no_copy_numbers` flag to `plassembler assembled` that should hopefully do what you want.

George

**Comment by gbouras13** [comment]
Hi @gaworj,

I've implemented this with `--no_copy_numbers` in the subcommand `plassembler assembled`

George
