### ISSUE TITLE
Pipeline failed No plasmid_long.fastq output

### ISSUE THREAD

**Issue by nbat64** [gbouras13/plassembler#43]
**Describe the bug**
Hello,
Thank you for your pipeline. I was able to run it without problem for some samples on a previous version (august).  I have upgraded to the version 1.5.0 add run with the following option:
````
plassembler run \
--database $DATABASE \
--longreads ${SAMPLE}.fastq \
--short_one ${SAMPLE}_R1.fastq \
--short_two ${SAMPLE}_R2.fastq \
--chromosome 4000000 \
--threads 48 \
--prefix $SAMPLE \
--force \
--min_quality $QUALITY \
--min_length $LENGTH \
--keep_chromosome \
--keep_fastqs \
--outdir ${SAMPLE}_output/
````
For several samples, the pipeline failed apparently after Flye with the following error message:
````
2023-12-04 16:12:09.304 | INFO     | plassembler:run:701 - Extracting Chromosome.
Traceback (most recent call last):
  File "/soft/2019013/Conda_env/plassembler_env/lib/python3.9/shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'IGLE11_output/plasmid_long.fastq' -> 'IGLE11_output/plasmid_fastqs/plasmids_long.fastq'
````
No plasmid_long.fastq have been produced. Do you know what could cause this error for some samples?  Could it be due to the quality of the Nanopore reads? Type of basecalling used (super mode min qscore of 7).

Thanks for the help and advice.

Regards,

Nicolas

**Comment by gbouras13** [comment]
Hi @nbat64 ,

I have run a few tests and have been unable to replicate this error.

I doubt it is due to the quality or base calling.

Are you running this on a cluster/HPC? It might have to do with file system latency or other issues with your system, the error suggests that you are running into a file does not exist error - so that might cause it.

George

**Comment by gbouras13** [comment]
Hi @nbat64 ,

With the first/original issue, if you re-run on the same samples, do you consistently get the issue? If not then I'd put it down to HPC problems. I've come across these filesystem issues running programs on HPC before (albeit not plassembler).

Trying a lower -c value and not keeping fastqs won't hurt if you don't need them.

George

**Comment by nbat64** [comment]
Hi George,
It is indeed a newly built Cluster and I had some weird behaviour with others scripts too... I will make more test on the HPC and outside.
Thanks, 
Nicolas

**Comment by gbouras13** [comment]
Closing as due to time
