### ISSUE TITLE
Raven could not be called for assembly

### ISSUE THREAD

**Issue by wanyuac** [gbouras13/plassembler#44]
**Describe the bug**
Flye was still used for assembly even if option `--use_raven` was specified.

**To Reproduce**
```
conda create -n plassembler
conda activate plassembler
conda install bioconda::plassembler=1.5.0
plassembler download -d ~/database/plassembler_20240130

plassembler run -l /data/reads/nanopore/sample_processed.fastq.gz -1 /data/reads/illumina/sample_1.fastq.gz -2 /data/reads/illumina/sample_2.fastq.gz -o sample_raven -p sample_plassembler_raven -d ~/database/plassembler_20240130 --use_raven -t 16 -c 5000000 --skip_qc -f
```

**Expected behavior**
Raven should be used for assembly instead of Flye when `--use_raven` is turned on.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux — Ubuntu 22.04.3 LTS
 - Conda v23.11.0

**Additional context**
Attached the log file and a list of software installed in my current conda environment for information.
[plassembler_1706654181.1144152.log](https://github.com/gbouras13/plassembler/files/14105274/plassembler_1706654181.1144152.log)
[conda_environment.txt](https://github.com/gbouras13/plassembler/files/14105284/conda_environment.txt)

**Comment by gbouras13** [comment]
Hi @wanyuac ,

Thanks for reporting this bug - I've fixed it in the dev branch and will release shortly.

George

**Comment by wanyuac** [comment]
Thank you for your prompt response. Please feel free to close this issue.
