### ISSUE TITLE
Provide additional options to be given to Unicycler

### ISSUE THREAD

**Issue by chen1i6c04** [gbouras13/plassembler#46]
Is it possible to provide options for control `unicycler`?
For some purpose, I hope can control some actions of unicycler.

e.g
```
plassembler run --unicycler_options " --no_rotate --spades_options --tmp-dir /tmp" 
```
Thank you for the great tool

Best

**Comment by gbouras13** [comment]
Hi @chen1i6c04,

Absolutely I will add this in the next v1.6.0 update.

George
