### ISSUE TITLE
Directory Deletion in Plassembler Database Download

### ISSUE THREAD

**Issue by andreagp96** [gbouras13/plassembler#49]
Hi @gbouras13!

I'm writing this feature request because the other day I was trying to download the database, and when I specified the <database directory>, I mistakenly used and existing directory. Subsequently, I realized that I had inadvertently deleted the entire directory containing two weeks' work (fortunately, the files were not critical, so I am in the process of redoing the work). When the issue occurred, I was initially unsure of what was happening, prompting me to retrace my steps to pinpoint the exact moment when everything was lost. Upon further investigation, I examined the plassembler db.py script located at src->plassembler->utils->db.py where I encountered the following instruction:

    # remvoe the directory
    if os.path.exists(db_dir):
        shutil.rmtree(db_dir)

While I find the program to be excellent and continue to use it, I would like to suggest either excluding this portion of the script or implementing a confirmation prompt before deleting any existing directories.

Thanks a lot!

Andrea

**Comment by gbouras13** [comment]
Hi @andreagp96 ,

I'm very sorry to hear about that - and I completely agree with your recommendation, this should ideally never happen. I'll put in a fix. And I'm happy to hear that you can regenerate the files!

George
